# TestCompile.yml
# Github workflow script to test compile all examples of an Arduino library repository.
#
# Copyright (C) 2020-2022  Armin Joachimsmeyer
# https://github.com/ArminJo/Github-Actions
#

# This is the name of the workflow, visible on GitHub UI.
name: TestCompile
on: 
  workflow_dispatch: # To run it manually
    description: 'manual build check'
  push:
    paths:
    - '**.ino'
    - '**.cpp'
    - '**.hpp'
    - '**.h'
    - '**TestCompile.yml'
jobs:
  build:
    name: Test compiling examples for Uno
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arduino-boards-fqbn:
          - arduino:avr:uno
          - arduino:avr:uno|CRYSTAL_20MHZ_ASSEMBLED
          - arduino:avr:uno|LOCAL_DEBUG

        include:
          - arduino-boards-fqbn: arduino:avr:uno|CRYSTAL_20MHZ_ASSEMBLED
            build-properties:
              All: -DCRYSTAL_20MHZ_ASSEMBLED

          - arduino-boards-fqbn: arduino:avr:uno|LOCAL_DEBUG
            build-properties:
              All: -DLOCAL_DEBUG

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Compile all examples
        uses: ArminJo/arduino-test-compile@master
        with:
#          required-libraries: EasyButtonAtInt01,SoftI2CMaster
          build-properties: ${{ toJson(matrix.build-properties) }}