# TestCompile.yml
# Github workflow script to test compile all examples of an Arduino library repository.
#
# Copyright (C) 2020-2022  Armin Joachimsmeyer
# https://github.com/ArminJo/Github-Actions
#

# This is the name of the workflow, visible on GitHub UI.
name: TestCompile
on: 
  workflow_dispatch: # To run it manually
    description: 'manual build check'
  push:
    paths:
    - '**.ino'
    - '**.cpp'
    - '**.hpp'
    - '**.h'
    - '**TestCompile.yml'
jobs:
  build:
    name: Test compiling examples for Nano / Uno
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arduino-boards-fqbn:
          - arduino:avr:nano
          - arduino:avr:uno
          - arduino:avr:uno|STANDALONE_TEST
          - arduino:avr:uno|DEBUG
          - arduino:avr:uno|DISPLAY_ALWAYS_ON
          - arduino:avr:uno|USE_NO_LCD
          - MightyCore:avr:644

        include:
          - arduino-boards-fqbn: arduino:avr:uno|STANDALONE_TEST
            build-properties:
              All: -DSTANDALONE_TEST

          - arduino-boards-fqbn: arduino:avr:uno|DEBUG
            build-properties:
              All: -DDEBUG

          - arduino-boards-fqbn: arduino:avr:uno|DISPLAY_ALWAYS_ON
            build-properties:
              All: -DDISPLAY_ALWAYS_ON

          - arduino-boards-fqbn: arduino:avr:uno|USE_NO_LCD
            build-properties:
              All: -DUSE_NO_LCD

          - arduino-boards-fqbn: MightyCore:avr:644
            platform-url: https://mcudude.github.io/MightyCore/package_MCUdude_MightyCore_index.json
            build-properties:
              All: -DUSE_LAYOUT_FOR_644_BOARD

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Compile all examples
        uses: ArminJo/arduino-test-compile@master
        with:
#          required-libraries: EasyButtonAtInt01,SoftI2CMaster
          arduino-board-fqbn: ${{ matrix.arduino-boards-fqbn }}
          platform-url: ${{ matrix.platform-url }}
          build-properties: ${{ toJson(matrix.build-properties) }}